

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"  
    networks:
      - app-network
    volumes:
      - mongodb_data:/data/db  
  nest-app:
    build:
      context: .  
    container_name: nest-app
    ports:
      - "3000:3000"  
    depends_on:
      - mongodb  
    networks:
      - app-network
    volumes:
      - .:/usr/src/app
    command: npm run start:dev  

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: